### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by shivika** [rapomon/geojson-places#10]
Hi,
I am trying to use this package and am getting the following error: 
```ERROR in ../node_modules/geojson-places/src/index.js 1:11-24
Module not found: Error: Can't resolve 'fs' in...
```
from this import in the index.js file
<img width="335" alt="image" src="https://github.com/rapomon/geojson-places/assets/3484166/0d02e804-7c67-48ac-a566-46d1c7441a69">

It doesn't seem to be listing in package.json either. Am I missing something? 

Thanks!

**Comment by rapomon** [comment]
The library is developed to be used with node.
