### ISSUE TITLE
Data auto update task

### ISSUE THREAD

**Issue by Portur** [rapomon/geojson-places#5]
Hi There,

Do you have any work/plan to implement an auto update of data from natural earth?

I have tried this myself and is quite cumbersome, but I don't mind moving that proces to this repo to ensure the data is updated atleast monthly.

**Comment by rapomon** [comment]
Hi.

I don't have any plan about it. It is something that I have always done manually.

Anyway, I updated the data in December 2022 with the latest and as today there are no new versions, you can check it at [https://github.com/nvkelso/natural-earth-vector/blob/master/CHANGELOG](https://github.com/nvkelso/natural-earth-vector/blob/master/CHANGELOG), here you will see that **ne_10m_admin-1** was last updated to version 5.1.1 on 2022-05-12.
